In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
import pickle
import joblib

In [2]:
data = pd.read_csv("RFData.csv")
print(data.head(5))
print(data.columns)
print(data['Frame3'])

   Age  Weight  Height  WearHours  WearYears  EyewearWeight  NoseArea  \
0   22      49     154         15        9.0           13.3     66.30   
1   23      64     171          0        0.0           21.4     95.94   
2   21      47     170         18       10.0           24.1     81.92   
3   21      51     164          2        0.0           21.4     95.94   
4   54      92     189         15       40.0           26.5    102.87   

   CurrentComfort  HeadWidth  Frame1  ...  PSport  PStudy  PCosmetic  \
0               8        147       8  ...       1       1          0   
1               8        155      10  ...       0       1          0   
2               8        156       9  ...       0       1          1   
3               8        148       9  ...       0       1          0   
4              10        157      10  ...       0       0          0   

   Gender_Female  Gender_Male  Race_Chinese  Race_Eurasian  Race_Indian  \
0              1            0             1          

In [4]:
labels_frame1 = data['Frame1']
labels_frame2 = data['Frame2']
labels_frame3 = data['Frame3']
features = data.drop(['Frame1', 'Frame2', 'Frame3'], axis = 1)

# drop unnecessary features
features = features.drop(['EarToFrame', 'EarToEye'], axis = 1)

labels_frame1 = np.array(labels_frame1)
labels_frame2 = np.array(labels_frame2)
labels_frame3 = np.array(labels_frame3)
features = np.array(features)

In [5]:
train_features1, test_features1, train_labels1, test_labels1 = train_test_split(features, labels_frame1, test_size = 0.25)
train_features2, test_features2, train_labels2, test_labels2 = train_test_split(features, labels_frame2, test_size = 0.25)
train_features3, test_features3, train_labels3, test_labels3 = train_test_split(features, labels_frame3, test_size = 0.25)

print('Training Features Shape:', train_features1.shape)
print('Training Labels Shape:', train_labels1.shape)
print('Testing Features Shape:', test_features1.shape)
print('Testing Labels Shape:', test_labels1.shape)

print(test_features1)

Training Features Shape: (150, 20)
Training Labels Shape: (150,)
Testing Features Shape: (51, 20)
Testing Labels Shape: (51,)
[[ 55.  54. 162. ...   0.   0.   0.]
 [ 21.  42. 151. ...   0.   0.   0.]
 [ 46.  82. 172. ...   0.   0.   0.]
 ...
 [ 19.  51. 177. ...   1.   0.   0.]
 [ 22.  46. 151. ...   0.   0.   0.]
 [ 21.  70. 164. ...   1.   0.   0.]]


In [6]:
model_frame1 = RandomForestRegressor()
model_frame2 = RandomForestRegressor()
model_frame3 = RandomForestRegressor()

model_frame1.fit(train_features1, train_labels1)
model_frame2.fit(train_features2, train_labels2)
model_frame3.fit(train_features3, train_labels3)

RandomForestRegressor()

In [8]:
prediction1 = model_frame1.predict(test_features1)
error1 = abs(prediction1 - test_labels1)
accuracy1 = 100  - np.mean(100 * (error1/test_labels1))

prediction2 = model_frame2.predict(test_features2)
error2 = abs(prediction2 - test_labels2)
accuracy2 = 100  - np.mean(100 * (error2/test_labels2))

prediction3 = model_frame3.predict(test_features3)
error3 = abs(prediction3 - test_labels3)
accuracy3 = 100  - np.mean(100 * (error3/test_labels3))

print(prediction3)
print(f"frame 1 accuracy: {round(accuracy1, 2)}%")
print(f"frame 2 accuracy: {round(accuracy2, 2)}%")
print(f"frame 3 accuracy: {round(accuracy3, 2)}%")

[3.68 3.89 3.94 4.79 3.28 3.34 3.83 3.97 4.84 4.41 4.49 3.12 5.32 3.42
 4.21 3.39 4.3  4.22 3.64 3.29 3.38 3.48 4.17 2.61 3.87 4.3  3.91 5.02
 4.43 5.02 3.38 3.38 6.01 3.43 4.86 2.61 4.54 3.47 4.01 3.19 3.48 3.37
 4.31 2.9  4.39 3.31 3.78 3.48 2.82 4.09 3.79]
frame 1 accuracy: 75.89%
frame 2 accuracy: 66.6%
frame 3 accuracy: 28.47%


In [9]:
joblib.dump(model_frame1, 'model_frame1.pkl')
joblib.dump(model_frame2, 'model_frame2.pkl')
joblib.dump(model_frame3, 'model_frame3.pkl')

['model_frame3.pkl']